// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TiendaServicios.Api.Shop.Persistence;

namespace TiendaServicios.Api.Shop.Migrations
{
    [DbContext(typeof(ContextShopping))]
    [Migration("20220529025445_MySqlMigrationInitial")]
    partial class MySqlMigrationInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("TiendaServicios.Api.Shop.Models.PedidoSesion", b =>
                {
                    b.Property<int>("PedidoSesionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.HasKey("PedidoSesionId");

                    b.ToTable("PedidoSesion");
                });

            modelBuilder.Entity("TiendaServicios.Api.Shop.Models.PedidoSesionDetalle", b =>
                {
                    b.Property<int>("PedidoSesionDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<int>("PedidoSesionId")
                        .HasColumnType("int");

                    b.Property<string>("ProductoSelected")
                        .HasColumnType("longtext");

                    b.HasKey("PedidoSesionDetalleId");

                    b.HasIndex("PedidoSesionId");

                    b.ToTable("PedidoSesionDetalle");
                });

            modelBuilder.Entity("TiendaServicios.Api.Shop.Models.PedidoSesionDetalle", b =>
                {
                    b.HasOne("TiendaServicios.Api.Shop.Models.PedidoSesion", "PedidoSesion")
                        .WithMany("Detalle")
                        .HasForeignKey("PedidoSesionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PedidoSesion");
                });

            modelBuilder.Entity("TiendaServicios.Api.Shop.Models.PedidoSesion", b =>
                {
                    b.Navigation("Detalle");
                });
#pragma warning restore 612, 618
        }
    }
}
